--//                                                  \\
--||   Project: MTA - German ICE Reallife Gamemode    ||
--||   Developers: PlayasEmre                         ||
--||   Version: 5.0                                   ||
--\\                                                  //

local allCommands = {
	["account"] = { 	"/newpw [neuesPW] [neuesPW] - Ändert das Passwort",
						"/self - Zeigt das Selfmenü",
						"/shader - Öffnet das Shader-Fenster",
						"/save - Speichert Position & Waffen und geht Offline" },
					
	["fahrzeug"] = {
						"/eject [Name/all] - Schmeißt jemanden/alle aus dem Auto",
						"/limit [km/h] - Setzt ein Tempolimit (Tempomat)",
						"/stoplimit - Deaktiviert den Tempomat",
						"/dellack - Löscht den Lack",
						"/fill - Benutzt einen Benzinkanister",
						"/vehhelp - Zeigt Befehle für Fahrzeuge",
						"/towveh [Slot] - Lässt dein Fahrzeug für 20€ respawnen (Abschleppen)",
						"/sellcarto [Name] [Preis] [Slot] - Bietet jemandem dein Fahrzeug zum Kauf an",
						"/buy - Nimmt das Kaufangebot eines Fahrzeugs an",
						"/park - Speichert die aktuelle Position deines Fahrzeugs",
						"/lock - Schließt/Öffnet dein Fahrzeug ab",
						"/tlock [Name] [Slot] - (Ent-)Sperrt ein Fahrzeug für den Schlüsselinhaber",
						"/vehinfos - Zeigt Informationen zu deinem Fahrzeug an",
						"/sellcar [Slot] - Verkauft dein Fahrzeug (NPC)",
						"/break - Löst/Zieht die Handbremse an",
						"/givekey [Name] [Slot] - Gibt jemandem einen Fahrzeugschlüssel",
						"/clearvehKey [Slot] - Entzieht den Fahrzeugschlüssel eines Slots",
						"/grabheli - Greift ein Fahrzeug mit dem Helikopter",
						"/dropheli - Lässt das gegriffene Fahrzeug fallen",
						"/forcedrop - Erzwingt das Fallenlassen des gegriffenen Fahrzeugs",
						"/verleihverlaengern - Verlängert die Mietdauer deines Mietfahrzeugs",
						"/verleihabgeben - Gibt dein Mietfahrzeug zurück",
						"/freikaufen [Slot] - Kauft ein abgeschlepptes Fahrzeug frei",
						"/gurt - Legt den Sicherheitsgurt an/ab" },
						
	["admin"] = { 		"/report - Öffnet das Report-Fenster",
						"/warns - Zeigt alle Warns an",
						"/checkwarns [Name] - Zeigt alle Warns eines Spielers an",
						"/admins - Zeigt alle Admins an",
						"/admincommands - Zeigt Adminbefehle für deinen Rang an" },

	["hochzeit"] = {	"/eheregister - Öffnet das Eheregister",
						"/lockkirche - Schließt/Öffnet die Kirche",
						"/acceptunmarry - Nimmt einen Scheidungsantrag an" },
	
	["polizei"] = { 	"/ergeben - Stellen mit Wanteds am PD",
						"/jailtime - Zeigt die verbleibende Knastzeit an",
						"/bail - Bezahlt die Kaution falls vorhanden",
						"/accept test - Nimmt den Drogentest vom Polizisten an",
						"/accept ticket - Nimmt ein Ticket vom Polizisten an" },
						
	["spiele"] = {
						"/dice - Würfelt",
						"/gluecksradticket - Kauft ein Ticket für das Glücksrad" },
						
	["job"] = {			"/job - Nimmt einen Job an",
						"/quitjob - Legt einen Job ab",
						"/zugjob - Startet Zugjob",
						"/endjob - Bricht Mülljob ab",
						"/sellhotdog [Preis] [Ziel] - Verkauft jemandem Hotdogs",
						"/accepthotdog - Nimmt das Angebot für den Hotdog an",
						"/cancel job - Bricht einen Job ab",	
						"/fish - Benutzt die Angel",
						"/sellfish [Slot] - Verkauft Fisch",
						"/gabelfixx - Bricht den Gabelstaplerjob ab",
						"/contract - Nimmt einen Auftragsmord-Vertrag an",
						"/contracts - Zeigt offene Auftragsmord-Verträge an" },
						
	["mats"] = {		"/buymats - Kauft Mats am Waffendealer-Jobmarker",
						"/gunhelp - Zeigt Matspreise der Waffen an",
						"/sellgun [Name] [Waffe] [Ammo] - Verkauft eine Waffe an jemanden" },
						
	["handy"] = {		"/handy - Zeigt das Handy",
						"/sms [Nummer] [Text] - Schreibt einer Nummer einen Text",
						"/call [Nummer] - Ruft eine Nummer an",
						"/hup - Legt auf",
						"/pup - Nimmt einen Anruf an",
						"/number [Name] - Ruft Nummer des Spielers auf" },
						
	["drogen"] = {		"/usedrugs - Benutzt Drogen",
						"/buydrugs [Anzahl] - Kauft Drogen",
						"/givedrugs [Ziel] [Anzahl] - Gibt jemandem Drogen", 
						"/grow weed - Pflanzt Drogen an" },
						
	["reporter"] = {	"/endlive - Beendet den Live-Chat",
						"/newspaper - Kauft eine Zeitung", 
						"/readnewspaper - Liest die Zeitung" },
	
	["sonstiges"] = {	"/ad [Text] - Schreibt eine Werbung",
						"/internet - Öffnet das Internet",
						"/animlist - Zeigt alle Animationen an",
						"/fglass - Benutzt das Fernglas",
						"/pay [Name] [Anzahl] - Zahlt jemandem Geld",
						"/rebind - Legt Nachladen auf R neu an",
						"/delmyobjects - Löscht alle eigenen platzierten Objekte",
						"/fraktioncommands - Zeigt alle Fraktionsbefehle an",
						"/ablegen - Legt die aktuelle Waffe ab",
						"/ablegenruckgangig - Nimmt die zuletzt abgelegte Waffe wieder auf",
						"/ego - Aktiviert die freie Egoperspektive-Kamera",
						"/quest - Zeigt/Versteckt die Quest-Aufgabenbox",
						"/gps - Öffnet die Navigation (im Fahrzeug)",
						"/stopgps - Beendet die aktive Navigation",
						"/race [Name] - Fordert jemanden zu einem Wettrennen heraus",
						"/showLevel - Zeigt dein Level an",
						"/fahrschule - Ruft einen Fahrlehrer zur Fahrschule",
						"/faccept [Lehrer] - Nimmt die Führerschein-Prüfung eines Lehrers an",
						"/fuehrerschein - Macht die Führerschein-Theorieprüfung",
						"/infos - Zeigt die Preise der Führerscheine an",
						},
	
	["haus"] = {		"/in - Betretet eine Wohnung",
						"/out - Verlässt eine Wohnung",
						"/rent - Mietet sich in eine Wohnung ein",
						"/unrent - Mietet sich aus einer Wohnung aus",
						"/sellhouse - Verkauft deine Wohnung",
						"/delhouse - Löscht den Haus-Marker",
						"/setrent [Preis/0] - Bestimmt die Miete deiner Wohnung",
						"/hlock - Öffnet/Schließt deine Wohnung",
						"/buyhouse [bar/bank] - Kauft eine Wohnung",
						"/garage - Öffnet/Schließt die Garage deiner Wohnung" },
						
	["club"] = {		"/quitclub - Kündigt Gartenclub-Mitgliedschaft",
						"/leaveclub - Kündigt Verein-/Club-Mitgliedschaft" },
						
	["schuss"] = {		"/reddot - Aktiviert Laservisier beim Zielen",
						"/hitglocke - Aktiviert Hitglocke beim Schießen" },
						
	["gang"] = {		"/creategang - Erstellt eine Gang",	
						"/leavegang - Verlässt die Gang",
						"/ganguninvite [Name] - Wirft jemanden aus der Gang (ab Rang 3)",
						"/ganginvite [Name] - Lädt jemanden in die Gang ein (ab Rang 3)",
						"/ganggiverank [Name] [Rang] - Gibt jemandem in der Gang einen Rang (ab Rang 3)" },
						
	["aktion"] = {		"/payrob - Bezahlt das Geld bei einem Überfall",
						"/parachute - Geht Fallschirmspringen (Flughafen)",
						"/aufgeben - Gibt beim Boxkampf auf",
						"/leavetactic - Verlässt den Tactic-Modus",
						},
						
	["chat"] = {		"/meCMD [Text] - Benutzt einen violetten Chat",
						"/s [Text] - Schreit",
						"/l [Text] - Flüstert" },
						
	["prestige"] = {	"/buyprestige - Kauft ein Prestige-Objekt",
						"/sellprestige - Verkauft das Prestige-Objekt" },
						
	["biz"] = {			"/buybiz [bar/bank] - Kauft ein Biz",
						"/sellbiz - Verkauft ein Biz",
						"/bizhelp - Zeigt Infos über das Biz an",
						"/bizdraw [Anzahl] - Nimmt Geld aus der Biz-Kasse",
						"/bizstore [Anzahl] - Zahlt Geld in die Biz-Kasse" },
	["tramjob"] = {		"/tramjob - Nimmt den Tramjob an",
						"/tramjobstart - Startet den Tramjob" },

	["premium"] = {		"/phelp - Zeigt Infos über dein Premium-Paket an",
						"/pcar [Slot] [Fahrzeug-ID] - Setzt eines deiner gratis Premium-Fahrzeuge",
						"/premstatus - Hinweis zur Statusänderung im Webpanel",
						"/tele - Hinweis zur Rufnummer-Änderung im Webpanel" },

	["event"] = {		"/halloween - Öffnet den Halloween-Stand (während des Events)",
						"/Kürbis - Süßes oder Saures an einer Haustür (während des Events)",
						"/zombieskin - Wechselt den Zombie-Skin (während des Events)",
						"/zombieende - Beendet die Zombie-Nacht" }
}


addCommandHandler ( "commands", function ( cmd, typ )
	if typ then
		if allCommands[typ] then
			outputChatBox ( "Befehle:", 200, 200, 200 )
			for i=1, #allCommands[typ] do
				outputChatBox ( allCommands[typ][i], 200, 200, 0 )
			end
		else
			outputChatBox ( "Gebrauch: /commands  [Kategorie]", 255, 0, 0 ) 
			outputChatBox ( "Möglich: account, fahrzeug, admin, polizei, spiele, job, mats, tramjob", 255, 0, 0 )
			outputChatBox ( "handy, drogen, reporter, sonstiges, haus, club, schuss, gang, aktion, chat, prestige, biz, hochzeit, premium, event", 255, 0, 0 )
		end
	else
		outputChatBox ( "Gebrauch: /commands  [Kategorie]", 255, 0, 0 )
		outputChatBox ( "Möglich: account, fahrzeug, admin, polizei, spiele, job, mats, tramjob", 255, 0, 0 )
		outputChatBox ( "handy, drogen, reporter, sonstiges, haus, club, schuss, gang, aktion, chat, prestige, biz, hochzeit, premium, event", 255, 0, 0 )
	end
end )



local allFactionCommands = {
	[1] = { 
		[0] = { "/mv - Öffnet die Tore/Schranken",
				"/t [Text] - Schreibt im Teamchat (Fraktion)",
				"/g [Text] - Schreibt im Beamtenchat",
				"/defusebomb - Entschärft die Bombe in der Bank",
				"/geldtruck - Startet einen Geldruck",
				"/abnehmen - Nimmt Geld beim Bankraub ab",
				"F2 - Tazert den nächsten Spieler",
				"/cuff [Name] - Legt einem Spieler Handschellen an",
				"/radarfalle - Aktiviert eine Radarfalle",
				"/needhelp - Bittet um Verstärkung", 
				"/ticket [Name] [Preis] - Bietet einem Wantler ein Ticket an",
				"/grab [Name] - Nimmt jemand getazerten ins Auto",
				"/fbank [Anzahl] - Zahlt Geld in die Fraktionskasse", 
				"/m [Text] - Benutzt das Megafon im Auto",
				"/givetest [Name] - Bietet jemandem ein Alkohol- & Drogentest an", 
				"/frisk [Name] - Durchsucht einen Spieler nach Illegalem",
				"/offduty - Geht Offduty", 
				"/delbomb - Bombe entschärfen", 
				"/takeillegal - Nimmt einem Spieler Illegales ab",
				"/duty - Geht Onduty", 
				"/su [Name] [Grund] - Gibt jemandem einen Wanted",
				"/suspect [Name] [Abk] - Gibt jemandem automatisch Wanteds",
				"/clear [Name] - Löscht alle Wanteds eines Spielers",
				"/stvopunkte [Name] [Grund] - Gibt jemandem einen StVO-Punkt",
				"/takeweapons [Name] - Entwaffnet einen Spieler",
				"/barricade - Platziert eine Barrikade",
				"/tie [Name] - Fesselt jemanden im Auto",
				"/fstate - Zeigt den Inhalt der Fraktionskasse an",
				"/selfuninvite - Verlässt die Fraktion",
				"/stopfrespawn - Stoppt ein Fraktions-Respawn",
				"/fraktion - Zeigt das Fraktionspanel",
				"/fskin - Wechselt den Skin falls mit /allowfskin erlaubt wurde",
				"/ansage - Spielt eine Polizei-Durchsage ab (im Fahrzeug)",
				"/vkk - Spielt eine VKK-Durchsage ab (im Fahrzeug)",
				"/gesucht - Spielt eine Fahndungs-Durchsage ab (im Fahrzeug)",
				"/vvkcall - Spielt eine VVK-Durchsage ab (im Fahrzeug)",
				"/vvk2 - Spielt eine zweite VVK-Durchsage ab (im Fahrzeug)",
				"/gurtkontrolle (oder /gk) - Kontrolliert den Gurt des nächstgelegenen Fahrers"},
		[1] = { "/stellen - Aktiviert/Deaktiviert das Stellen" },
		[2] = { "/ausknasten [Ziel] - Knastet jemanden aus",
				"/delstvo [Name] [Anzahl] [Grund] - Löscht einem Spieler die StVO-Punkte",
				"/frespawn - Startet einen Fraktionsrespawn",
				"/presikonvoi - Startet einen Präsidenten-Konvoi"},
		[3] = { "/takegunlicense [Ziel] - Nimmt jemanden den Waffenschein weg",
				"/ram - Betretet eine Wohnung unabhängig von hlock",
				"/nailload - Lädt Nagelbänder ins Auto",
				"/takenail [Anzahl] - Nimmt Nagelbänder aus dem Auto",
				"/nail - Legt ein Nagelband",
				"/rnail - Löscht das eigene Nagelband" },
		[4] = { "/rnail - Löscht ein bestimmtes Nagelband",
				"/invite [Name] - Nimmt jemanden in die Fraktion auf",
				"/uninvite [Name] - Wirft jemanden aus der Fraktion raus", 
				"/getchangestate [Name] - Prüft letzten Invite/Uninvite des Spielers", 
				"/giverank [Name] [Rang] - Gibt einem Fraktionsmitglied einen Rang",
				"/allowfskin - Erlaubt /fskin für 2 Minuten",
				"/frakpm [Text] - Schickt jedem Mitglied eine Nachricht (auch offline)" },
		[5] = { "/cell - Öffnet alle Zellentüren",
				"/fdraw [Anzahl] - Nimmt Geld aus der Fraktionskasse",
				"/rnails - Löscht alle platzierten Nagelbänder"	}
	},
	[2] = {
		[0] = { "/mv - Öffnet die Tore/Schranken",
				"/t [Text] - Schreibt im Teamchat (Fraktion)",
				"/b [Text] - Schreibt im böse-Fraktions-Chat",
				"/matstruck - Startet einen Matstruck für 5.000€",
				"/robbank - Raubt die Bank aus",
				"/rob [Name] - Raubt einen Zivilisten aus",
				"/drogentruck - Startet einen Drogentruck",
				"/gibwaffe - Gibt eine Waffe falls beim Casinorob gewonnen",
				"/carrob - Startet einen Carrob",
				"/car - Startet einen zweiten Carrob (Autohaus)",
				"/bankrob - Startet einen Bankraub",
				"/gwbefehle - Zeigt alle Gangwarbefehle an",
				"/fguns - Öffnet das Fguns-Menü",
				"/blacklist delete [Name] - Löscht jemanden aus der Blacklist",
				"/blacklist show - Zeigt die Blacklist an",
				"/tie [Name] - Fesselt jemanden im Auto",
				"/fstate - Zeigt den Inhalt der Fraktionskasse an",
				"/fskin - Zieht einen anderen Skin an",
				"/selfuninvite - Verlässt die Fraktion",
				"/stopfrespawn - Stoppt ein Fraktions-Respawn",
				"/befreien [Name] - Befreit einen inhaftierten Spieler aus dem Gefängnis",
				"/robcasino - Startet einen Casinoraub",
				"/defuse - Entschärft die Bombe beim Casinoraub",
				"/fraktion - Zeigt das Fraktionspanel" },
		[2] = { "/frespawn - Startet einen Fraktionsrespawn" },
		[3] = { "/blacklist add [Name] [Grund] - Setzt einen Zivilisten auf die Blacklist" },
		[4] = { "/invite [Name] - Nimmt jemanden in die Fraktion auf",
				"/uninvite [Name] - Wirft jemanden aus der Fraktion raus", 
				"/getchangestate [Name] - Prüft letzten Invite/Uninvite des Spielers",
				"/giverank [Name] [Rang] - Gibt einem Fraktionsmitglied einen Rang",
				"/frakpm [Text] - Schickt jedem Mitglied eine Nachricht (auch offline)" }
	},
	[3] = {
		[0] = { "/mv - Öffnet die Tore/Schranken",
				"/t [Text] - Schreibt im Teamchat (Fraktion)",
				"/b [Text] - Schreibt im böse-Fraktions-Chat",
				"/matstruck - Startet einen Matstruck für 5.000€",
				"/robbank - Raubt die Bank aus",
				"/rob [Name] - Raubt einen Zivilisten aus",
				"/drogentruck - Startet einen Drogentruck",
				"/gibwaffe - Gibt eine Waffe falls beim Casinorob gewonnen",
				"/carrob - Startet einen Carrob",
				"/car - Startet einen zweiten Carrob (Autohaus)",
				"/bankrob - Startet einen Bankraub",
				"/gwbefehle - Zeigt alle Gangwarbefehle an",
				"/fguns - Öffnet das Fguns-Menü",
				"/blacklist delete [Name] - Löscht jemanden aus der Blacklist",
				"/blacklist show - Zeigt die Blacklist an",
				"/tie [Name] - Fesselt jemanden im Auto",
				"/fstate - Zeigt den Inhalt der Fraktionskasse an",
				"/fskin - Zieht einen anderen Skin an",
				"/selfuninvite - Verlässt die Fraktion", 
				"/stopfrespawn - Stoppt ein Fraktions-Respawn",
				"/befreien [Name] - Befreit einen inhaftierten Spieler aus dem Gefängnis",
				"/robcasino - Startet einen Casinoraub",
				"/defuse - Entschärft die Bombe beim Casinoraub",
				"/fraktion - Zeigt das Fraktionspanel" },
		[2] = { "/frespawn - Startet einen Fraktionsrespawn" },
		[3] = { "/blacklist add [Name] [Grund] - Setzt einen Zivilisten auf die Blacklist" },
		[4] = { "/invite [Name] - Nimmt jemanden in die Fraktion auf",
				"/uninvite [Name] - Wirft jemanden aus der Fraktion raus", 
				"/getchangestate [Name] - Prüft letzten Invite/Uninvite des Spielers",
				"/giverank [Name] [Rang] - Gibt einem Fraktionsmitglied einen Rang",
				"/frakpm [Text] - Schickt jedem Mitglied eine Nachricht (auch offline)" }
	},
	[4] = {
		[0] = { "/mv - Öffnet die Tore/Schranken",
				"/t [Text] - Schreibt im Teamchat (Fraktion)",
				"/b [Text] - Schreibt im böse-Fraktions-Chat",
				"/matstruck - Startet einen Matstruck für 5.000€",
				"/detonate - Zündet die Bombe",
				"/fguns - Waffen und C4 am Waffenlager",
				"/arm - Rüstet sich mit Bomben aus",
				"/robbank - Raubt die Bank aus",
				"/rob [Name] - Raubt einen Zivilisten aus",
				"/drogentruck - Startet einen Drogentruck",
				"/gibwaffe - Gibt eine Waffe falls beim Casinorob gewonnen",
				"/carrob - Startet einen Carrob",
				"/car - Startet einen zweiten Carrob (Autohaus)",
				"/bankrob - Startet einen Bankraub",
				"/gwbefehle - Zeigt alle Gangwarbefehle an",
				"/blacklist delete [Name] - Löscht jemanden aus der Blacklist",
				"/blacklist show - Zeigt die Blacklist an",
				"/tie [Name] - Fesselt jemanden im Auto",
				"/fstate - Zeigt den Inhalt der Fraktionskasse an",
				"/fskin - Zieht einen anderen Skin an",
				"/selfuninvite - Verlässt die Fraktion",
				"/stopfrespawn - Stoppt ein Fraktions-Respawn",
				"/befreien [Name] - Befreit einen inhaftierten Spieler aus dem Gefängnis",
				"/robcasino - Startet einen Casinoraub",
				"/defuse - Entschärft die Bombe beim Casinoraub",
				"/fraktion - Zeigt das Fraktionspanel" },
		[2] = { "/frespawn - Startet einen Fraktionsrespawn" },
		[3] = { "/blacklist add [Name] [Grund] - Setzt einen Zivilisten auf die Blacklist" },
		[4] = { "/invite [Name] - Nimmt jemanden in die Fraktion auf",
				"/uninvite [Name] - Wirft jemanden aus der Fraktion raus", 
				"/getchangestate [Name] - Prüft letzten Invite/Uninvite des Spielers",
				"/giverank [Name] [Rang] - Gibt einem Fraktionsmitglied einen Rang", 
				"/katjuscha - Erstellt einen Katjuscha",
				"/c4 - Platziert eine C4-Bombe",
				"/c4back - Entfernt die platzierte C4-Bombe",
				"/detonatec4 - Zündet die platzierte C4-Bombe",
				"/bombe - Erstellt eine Bombe",
				"/frakpm [Text] - Schickt jedem Mitglied eine Nachricht (auch offline)" }
	},
	[5] = {
		[0] = { "/mv - Öffnet die Tore/Schranken", 
				"/t [Text] - Schreibt im Teamchat (Fraktion)",
				"/lift - Benutzt den Aufzug",
				"/news [Text] - Schreibt im News-Chat", 
				"/live [Name] - Schaltet jemanden in den Live-Chat", 
				"/endlive - Beendet den Live-Chat",
				"/reporterstart - Platziert einen Start-Blip an der Position",
				"/reporterende - Platziert einen Ende-Blip an der Position",
				"/delreporterstart - Löscht den Start-Blip",
				"/delreporterende - Löscht den Ende-Blip",
				"/fstate - Zeigt den Inhalt der Fraktionskasse an",
				"/fskin - Zieht einen anderen Skin an",
				"/selfuninvite - Verlässt die Fraktion", 
				"/stopfrespawn - Stoppt ein Fraktions-Respawn", 
				"/fraktion - Zeigt das Fraktionspanel" },
		[2] = { "/frespawn - Startet einen Fraktionsrespawn" },
		[3] = { "/edit - Bearbeitet die Zeitung" },
		[4] = { "/delallreporterblips - Löscht alle Reporter-Blips",
				"/invite [Name] - Nimmt jemanden in die Fraktion auf",
				"/uninvite [Name] - Wirft jemanden aus der Fraktion raus", 
				"/getchangestate [Name] - Prüft letzten Invite/Uninvite des Spielers",
				"/giverank [Name] [Rang] - Gibt einem Fraktionsmitglied einen Rang",
				"/frakpm [Text] - Schickt jedem Mitglied eine Nachricht (auch offline)" }
	},
	[6] = {
		[0] = { "/mv - Öffnet die Tore/Schranken",
				"/t [Text] - Schreibt im Teamchat (Fraktion)",
				"/g [Text] - Schreibt im Beamtenchat",
				"/defusebomb - Entschärft die Bombe in der Bank",
				"/geldtruck - Startet einen Geldruck",
				"/abnehmen - Nimmt Geld beim Bankraub ab",
				"F2 - Tazert den nächsten Spieler",
				"/cuff [Name] - Legt einem Spieler Handschellen an",
				"/needhelp - Bittet um Verstärkung",
				"/ticket [Name] [Preis] - Bietet einem Wantler ein Ticket an",
				"/grab [Name] - Nimmt jemand getazerten ins Auto",
				"/fbank [Anzahl] - Zahlt Geld in die Fraktionskasse",
				"/m [Text] - Benutzt das Megafon im Auto",
				"/givetest [Name] - Bietet jemandem ein Alkohol- & Drogentest an",
				"/frisk [Name] - Durchsucht einen Spieler nach Illegalem",
				"/offduty - Geht Offduty",
				"/takeillegal - Nimmt einem Spieler Illegales ab",
				"/duty - Geht Onduty",
				"/su [Name] [Grund] - Gibt jemandem einen Wanted",
				"/suspect [Name] [Abk] - Gibt jemandem automatisch Wanteds",
				"/clear [Name] - Löscht alle Wanteds eines Spielers",
				"/stvopunkte [Name] [Grund] - Gibt jemandem einen StVO-Punkt",
				"/takeweapons [Name] - Entwaffnet einen Spieler",
				"/wanze - Legt eine Wanze",
				"/barricade - Platziert eine Barrikade", 
				"/tie [Name] - Fesselt jemanden im Auto",
				"/fstate - Zeigt den Inhalt der Fraktionskasse an",
				"/fskin - Zieht einen anderen Skin an",
				"/selfuninvite - Verlässt die Fraktion",
				"/stopfrespawn - Stoppt ein Fraktions-Respawn",
				"/fraktion - Zeigt das Fraktionspanel",
				"/ansage - Spielt eine Polizei-Durchsage ab (im Fahrzeug)",
				"/vkk - Spielt eine VKK-Durchsage ab (im Fahrzeug)",
				"/gesucht - Spielt eine Fahndungs-Durchsage ab (im Fahrzeug)",
				"/vvkcall - Spielt eine VVK-Durchsage ab (im Fahrzeug)",
				"/vvk2 - Spielt eine zweite VVK-Durchsage ab (im Fahrzeug)",
				"/gurtkontrolle (oder /gk) - Kontrolliert den Gurt des nächstgelegenen Fahrers" },
		[1] = { "/stellen - Aktiviert/Deaktiviert das Stellen" },
		[2] = { "/ausknasten [Ziel] - Knastet jemanden aus",
				"/delstvo [Name] [Anzahl] [Grund] - Löscht einem Spieler die StVO-Punkte",
				"/killwanze [1-3] - Löscht eine der Wanzen",
				"/frespawn - Startet einen Fraktionsrespawn",
				"/presikonvoi - Startet einen Präsidenten-Konvoi" },
		[3] = { "/takegunlicense [Ziel] - Nimmt jemanden den Waffenschein weg",
				"/ram - Betretet eine Wohnung unabhängig von hlock",
				"/nailload - Lädt Nagelbänder ins Auto",
				"/takenail [Anzahl] - Nimmt Nagelbänder aus dem Auto",
				"/nail - Legt ein Nagelband",
				"/rnail - Löscht das eigene Nagelband" },
		[4] = { "/rnail - Löscht ein bestimmtes Nagelband",
				"/invite [Name] - Nimmt jemanden in die Fraktion auf",
				"/uninvite [Name] - Wirft jemanden aus der Fraktion raus", 
				"/getchangestate [Name] - Prüft letzten Invite/Uninvite des Spielers",
				"/giverank [Name] [Rang] - Gibt einem Fraktionsmitglied einen Rang",
				"/frakpm [Text] - Schickt jedem Mitglied eine Nachricht (auch offline)" },
		[5] = { "/cell - Öffnet alle Zellentüren",
				"/fdraw [Anzahl] - Nimmt Geld aus der Fraktionskasse",
				"/rnails - Löscht alle platzierten Nagelbänder" }
	},
	[7] = { 
		[0] = { "/mv - Öffnet die Tore/Schranken",
				"/t [Text] - Schreibt im Teamchat (Fraktion)",
				"/b [Text] - Schreibt im böse-Fraktions-Chat",
				"/matstruck - Startet einen Matstruck für 5.000€",
				"/robbank - Raubt die Bank aus",
				"/rob [Name] - Raubt einen Zivilisten aus",
				"/drogentruck - Startet einen Drogentruck",
				"/gibwaffe - Gibt eine Waffe falls beim Casinorob gewonnen",
				"/carrob - Startet einen Carrob",
				"/car - Startet einen zweiten Carrob (Autohaus)",
				"/bankrob - Startet einen Bankraub",
				"/gwbefehle - Zeigt alle Gangwarbefehle an",
				"/fguns - Öffnet das Fguns-Menü",
				"/blacklist delete [Name] - Löscht jemanden aus der Blacklist",
				"/blacklist show - Zeigt die Blacklist an",
				"/tie [Name] - Fesselt jemanden im Auto",
				"/fstate - Zeigt den Inhalt der Fraktionskasse an",
				"/fskin - Zieht einen anderen Skin an",
				"/selfuninvite - Verlässt die Fraktion", 
				"/stopfrespawn - Stoppt ein Fraktions-Respawn",
				"/befreien [Name] - Befreit einen inhaftierten Spieler aus dem Gefängnis",
				"/robcasino - Startet einen Casinoraub",
				"/defuse - Entschärft die Bombe beim Casinoraub",
				"/fraktion - Zeigt das Fraktionspanel" },
		[2] = { "/frespawn - Startet einen Fraktionsrespawn" },
		[3] = { "/blacklist add [Name] [Grund] - Setzt einen Zivilisten auf die Blacklist" },
		[4] = { "/invite [Name] - Nimmt jemanden in die Fraktion auf",
				"/uninvite [Name] - Wirft jemanden aus der Fraktion raus", 
				"/getchangestate [Name] - Prüft letzten Invite/Uninvite des Spielers",
				"/giverank [Name] [Rang] - Gibt einem Fraktionsmitglied einen Rang",
				"/frakpm [Text] - Schickt jedem Mitglied eine Nachricht (auch offline)" }
	},
	[8] = {
		[0] = { "/mv - Öffnet die Tore/Schranken",
				"/t [Text] - Schreibt im Teamchat (Fraktion)",
				"/g [Text] - Schreibt im Beamtenchat",
				"/defusebomb - Entschärft die Bombe in der Bank",
				"/geldtruck - Startet einen Geldruck",
				"/abnehmen - Nimmt Geld beim Bankraub ab",
				"Taste 1 - Tazert den nächsten Spieler",
				"/cuff [Name] - Legt einem Spieler Handschellen an",
				"/needhelp - Bittet um Verstärkung",
				"/ticket [Name] [Preis] - Bietet einem Wantler ein Ticket an",
				"/grab [Name] - Nimmt jemand getazerten ins Auto",
				"/fbank [Anzahl] - Zahlt Geld in die Fraktionskasse",
				"/m [Text] - Benutzt das Megafon im Auto",
				"/givetest [Name] - Bietet jemandem ein Alkohol- & Drogentest an",
				"/frisk [Name] - Durchsucht einen Spieler nach Illegalem",
				"/takeillegal - Nimmt einem Spieler Illegales ab",
				"/su [Name] [Grund] - Gibt jemandem einen Wanted",
				"/suspect [Name] [Abk] - Gibt jemandem automatisch Wanteds",
				"/clear [Name] - Löscht alle Wanteds eines Spielers",
				"/stvopunkte [Name] [Grund] - Gibt jemandem einen StVO-Punkt",
				"/takeweapons [Name] - Entwaffnet einen Spieler",
				"/barricade - Platziert eine Barrikade", 
				"/class [Klasse] - Setzt sich eine Klasse",
				"/tie [Name] - Fesselt jemanden im Auto",
				"/fstate - Zeigt den Inhalt der Fraktionskasse an",
				"/fskin - Zieht einen anderen Skin an und geht Onduty",
				"/offduty - Geht in den Ziviskin",
				"/selfuninvite - Verlässt die Fraktion",
				"/stopfrespawn - Stoppt ein Fraktions-Respawn",
				"/fraktion - Zeigt das Fraktionspanel",
				"/ansage - Spielt eine Polizei-Durchsage ab (im Fahrzeug)",
				"/vkk - Spielt eine VKK-Durchsage ab (im Fahrzeug)",
				"/gesucht - Spielt eine Fahndungs-Durchsage ab (im Fahrzeug)",
				"/vvkcall - Spielt eine VVK-Durchsage ab (im Fahrzeug)",
				"/vvk2 - Spielt eine zweite VVK-Durchsage ab (im Fahrzeug)",
				"/gurtkontrolle (oder /gk) - Kontrolliert den Gurt des nächstgelegenen Fahrers",
				"/atrans - Startet den Atomtransport (AT)" },
		[1] = { "/stellen - Aktiviert/Deaktiviert das Stellen",
				"/sandbag - Platziert einen Sandbag (Pionier)",
				"/explosive - Platziert einen Sprengsatz (Pionier)" },
		[2] = { "/ausknasten [Ziel] - Knastet jemanden aus",
				"/delstvo [Name] [Anzahl] [Grund] - Löscht einem Spieler die StVO-Punkte",
				"/frespawn - Startet einen Fraktionsrespawn",
				"/presikonvoi - Startet einen Präsidenten-Konvoi" },
		[3] = { "/takegunlicense [Ziel] - Nimmt jemanden den Waffenschein weg",
				"/ram - Betretet eine Wohnung unabhängig von hlock",
				"/nailload - Lädt Nagelbänder ins Auto", 
				"/takenail [Anzahl] - Nimmt Nagelbänder aus dem Auto",
				"/nail - Legt ein Nagelband",
				"/rnail - Löscht das eigene Nagelband" },
		[4] = { "/rnail - Löscht ein bestimmtes Nagelband",
				"/airstrike - Startet einen Luftanschlag",
				"/invite [Name] - Nimmt jemanden in die Fraktion auf",
				"/uninvite [Name] - Wirft jemanden aus der Fraktion raus", 
				"/getchangestate [Name] - Prüft letzten Invite/Uninvite des Spielers",
				"/giverank [Name] [Rang] - Gibt einem Fraktionsmitglied einen Rang",
				"/frakpm [Text] - Schickt jedem Mitglied eine Nachricht (auch offline)" },
		[5] = { "/cell - Öffnet alle Zellentüren",
				"/fdraw [Anzahl] - Nimmt Geld aus der Fraktionskasse",
				"/rnails - Löscht alle platzierten Nagelbänder",
				"/setpermission [Name] [1-9] [0/1] - Gibt eine Permission",
				"/setpermission [Name] [10] [0-100] - Gibt eine GWD Note" }
	},
	[9] = {
		[0] = { "/mv - Öffnet die Tore/Schranken",
				"/t [Text] - Schreibt im Teamchat (Fraktion)",
				"/b [Text] - Schreibt im böse-Fraktions-Chat",
				"/matstruck - Startet einen Matstruck für 5.000€",
				"/robbank - Raubt die Bank aus",
				"/rob [Name] - Raubt einen Zivilisten aus",
				"/drogentruck - Startet einen Drogentruck",
				"/gibwaffe - Gibt eine Waffe falls beim Casinorob gewonnen",
				"/carrob - Startet einen Carrob",
				"/car - Startet einen zweiten Carrob (Autohaus)",
				"/bankrob - Startet einen Bankraub", 
				"/gwbefehle - Zeigt alle Gangwarbefehle an", 
				"/fguns - Öffnet das Fguns-Menü",
				"/blacklist delete [Name] - Löscht jemanden aus der Blacklist",	
				"/blacklist show - Zeigt die Blacklist an",
				"/tie [Name] - Fesselt jemanden im Auto",
				"/fstate - Zeigt den Inhalt der Fraktionskasse an",	
				"/fskin - Zieht einen anderen Skin an",
				"/selfuninvite - Verlässt die Fraktion", 
				"/stopfrespawn - Stoppt ein Fraktions-Respawn", 
				"/befreien [Name] - Befreit einen inhaftierten Spieler aus dem Gefängnis",
				"/robcasino - Startet einen Casinoraub",
				"/defuse - Entschärft die Bombe beim Casinoraub",
				"/fraktion - Zeigt das Fraktionspanel" },
		[2] = { "/frespawn - Startet einen Fraktionsrespawn" },
		[3] = { "/blacklist add [Name] [Grund] - Setzt einen Zivilisten auf die Blacklist",
				"/formation - Erstellt eine Formation mit einer Freeway" },
		[4] = { "/invite [Name] - Nimmt jemanden in die Fraktion auf",
				"/uninvite [Name] - Wirft jemanden aus der Fraktion raus", 
				"/getchangestate [Name] - Prüft letzten Invite/Uninvite des Spielers",
				"/giverank [Name] [Rang] - Gibt einem Fraktionsmitglied einen Rang",
				"/frakpm [Text] - Schickt jedem Mitglied eine Nachricht (auch offline)" }
	},
	[10] = {
		[0] = { "/mv - Öffnet die Tore/Schranken", 
				"/t [Text] - Schreibt im Teamchat (Fraktion)",
				"/g [Text] - Schreibt im Beamtenchat",
				"/fstate - Zeigt den Inhalt der Fraktionskasse an",
				"/selfuninvite - Verlässt die Fraktion",
				"/stopfrespawn - Stoppt ein Fraktions-Respawn",
				"/komme [Name] - Nimmt ein Hilferuf an",
				"/medic - Öffnet das Sanitäter-Menü",
				"/loadmedikits - Lädt Medikits am Marker",
				"/usekit [Name] - Benutzt ein Medikit an jemandem",
				"/mlift [Name] - Hebt/Lädt einen Spieler in/aus dem Fahrzeug",
				"/fraktion - Zeigt das Fraktionspanel" },
		[2] = { "/frespawn - Startet einen Fraktionsrespawn" },
		[4] = { "/invite [Name] - Nimmt jemanden in die Fraktion auf",
				"/uninvite [Name] - Wirft jemanden aus der Fraktion raus",
				"/getchangestate [Name] - Prüft letzten Invite/Uninvite des Spielers",
				"/giverank [Name] [Rang] - Gibt einem Fraktionsmitglied einen Rang",
				"/frakpm [Text] - Schickt jedem Mitglied eine Nachricht (auch offline)" }
	},
	[11] = {
		[0] = { "/mv - Öffnet die Tore/Schranken",
				"/t [Text] - Schreibt im Teamchat (Fraktion)",
				"/g [Text] - Schreibt im Beamtenchat",
				"/fstate - Zeigt den Inhalt der Fraktionskasse an",
				"/selfuninvite - Verlässt die Fraktion",
				"/stopfrespawn - Stoppt ein Fraktions-Respawn",
				"/komme [Name] - Nimmt ein Hilferuf an",
				"/repaircar - Repariert das eigene Fahrzeug mit einem Repairkit",
				"/mlift [Name] - Hebt/Lädt einen Spieler in/aus dem Fahrzeug",

				"/fraktion - Zeigt das Fraktionspanel" },
		[2] = { "/frespawn - Startet einen Fraktionsrespawn" },
		[4] = { "/invite [Name] - Nimmt jemanden in die Fraktion auf",
				"/uninvite [Name] - Wirft jemanden aus der Fraktion raus", 
				"/getchangestate [Name] - Prüft letzten Invite/Uninvite des Spielers",
				"/giverank [Name] [Rang] - Gibt einem Fraktionsmitglied einen Rang",
				"/frakpm [Text] - Schickt jedem Mitglied eine Nachricht (auch offline)" }
	},
	[12] = {
		[0] = { "/mv - Öffnet die Tore/Schranken",
				"/t [Text] - Schreibt im Teamchat (Fraktion)",
				"/b [Text] - Schreibt im böse-Fraktions-Chat",
				"/matstruck - Startet einen Matstruck für 5.000€",
				"/robbank - Raubt die Bank aus",
				"/rob [Name] - Raubt einen Zivilisten aus",
				"/drogentruck - Startet einen Drogentruck",
				"/gibwaffe - Gibt eine Waffe falls beim Casinorob gewonnen",
				"/carrob - Startet einen Carrob",
				"/car - Startet einen zweiten Carrob (Autohaus)",
				"/bankrob - Startet einen Bankraub",
				"/gwbefehle - Zeigt alle Gangwarbefehle an",
				"/fguns - Öffnet das Fguns-Menü",
				"/blacklist delete [Name] - Löscht jemanden aus der Blacklist",
				"/blacklist show - Zeigt die Blacklist an",
				"/tie [Name] - Fesselt jemanden im Auto",
				"/fstate - Zeigt den Inhalt der Fraktionskasse an",
				"/fskin - Zieht einen anderen Skin an",
				"/selfuninvite - Verlässt die Fraktion", 
				"/stopfrespawn - Stoppt ein Fraktions-Respawn",
				"/befreien [Name] - Befreit einen inhaftierten Spieler aus dem Gefängnis",
				"/robcasino - Startet einen Casinoraub",
				"/defuse - Entschärft die Bombe beim Casinoraub",
				"/fraktion - Zeigt das Fraktionspanel" },
		[2] = { "/frespawn - Startet einen Fraktionsrespawn" },
		[3] = { "/blacklist add [Name] [Grund] - Setzt einen Zivilisten auf die Blacklist" },
		[4] = { "/invite [Name] - Nimmt jemanden in die Fraktion auf",
				"/uninvite [Name] - Wirft jemanden aus der Fraktion raus", 
				"/getchangestate [Name] - Prüft letzten Invite/Uninvite des Spielers",
				"/giverank [Name] [Rang] - Gibt einem Fraktionsmitglied einen Rang",
				"/frakpm [Text] - Schickt jedem Mitglied eine Nachricht (auch offline)" }
	},
	[13] = {
		[0] = { "/mv - Öffnet die Tore/Schranken",
				"/t [Text] - Schreibt im Teamchat (Fraktion)",
				"/b [Text] - Schreibt im böse-Fraktions-Chat",
				"/matstruck - Startet einen Matstruck für 5.000€",
				"/robbank - Raubt die Bank aus",
				"/rob [Name] - Raubt einen Zivilisten aus",
				"/drogentruck - Startet einen Drogentruck",
				"/gibwaffe - Gibt eine Waffe falls beim Casinorob gewonnen",
				"/carrob - Startet einen Carrob",
				"/car - Startet einen zweiten Carrob (Autohaus)",
				"/bankrob - Startet einen Bankraub", 
				"/gwbefehle - Zeigt alle Gangwarbefehle an",
				"/fguns - Öffnet das Fguns-Menü", 
				"/blacklist delete [Name] - Löscht jemanden aus der Blacklist",
				"/blacklist show - Zeigt die Blacklist an",
				"/tie [Name] - Fesselt jemanden im Auto",
				"/fstate - Zeigt den Inhalt der Fraktionskasse an",
				"/fskin - Zieht einen anderen Skin an",
				"/selfuninvite - Verlässt die Fraktion", 
				"/stopfrespawn - Stoppt ein Fraktions-Respawn",
				"/befreien [Name] - Befreit einen inhaftierten Spieler aus dem Gefängnis",
				"/robcasino - Startet einen Casinoraub",
				"/defuse - Entschärft die Bombe beim Casinoraub",
				"/fraktion - Zeigt das Fraktionspanel" },
		[2] = { "/frespawn - Startet einen Fraktionsrespawn" },
		[3] = { "/blacklist add [Name] [Grund] - Setzt einen Zivilisten auf die Blacklist" },
		[4] = { "/invite [Name] - Nimmt jemanden in die Fraktion auf",
				"/uninvite [Name] - Wirft jemanden aus der Fraktion raus", 
				"/getchangestate [Name] - Prüft letzten Invite/Uninvite des Spielers",
				"/giverank [Name] [Rang] - Gibt einem Fraktionsmitglied einen Rang",
				"/frakpm [Text] - Schickt jedem Mitglied eine Nachricht (auch offline)" },
			},	
	[14] = {
		[0] = {"/hackbhf - Hackt den Geldautomaten am Bahnhof",
			   "/hacknoob - Hackt den Geldautomaten am Noobspawn",
			   "/hackstadt - Hackt den Geldautomaten an der Stadthalle",
			   "/hackwangcars - Hackt den Geldautomaten bei Wang Cars",
			   "/hackhandy [Name] - Hackt das Handy eines Spielers und schaltet es an/aus",
			   "/hackwanteds [Name] - Löscht die Wanteds eines Spielers",
			   "/matstruck - Startet einen Matstruck für 5.000€"
			  }
			},

	[15] = {
		[0] = {"/fduty - Geht in den Dienst",
			   "/foffduty - Verlässt den Dienst",
			   "/fpruefung [Name] [Schein] - Bietet einem Spieler eine Fahrstunde an",
			   "/stoppruefung [Name] - Übergibt einem Spieler seine Lizenz",
			   "/finfo - Zeigt die Fahrlehrer-Befehlsübersicht an",
			  }
	},
}


addCommandHandler ( "fraktioncommands", function ( cmd, rang )
	if rang then
		local rang = tonumber ( rang )
		local frac = getElementData ( localPlayer, "fraktion" )
		if frac > 0 then
			if rang and rang >= 0 and rang <= 5 then
				local wasthere = false
				outputChatBox ( "Befehle:", 200, 200, 200 )
				if allFactionCommands[frac][rang] then
					for i=1, #allFactionCommands[frac][rang] do
						outputChatBox ( allFactionCommands[frac][rang][i], 200, 200, 0 )
						wasthere = true
					end
				end
				if not wasthere then
					outputChatBox ( "Keine für diesen Rang spezifische!", 255, 0, 0 )
				end
			else
				outputChatBox ( "Gebrauch: /fraktioncommands  [0-5]", 255, 0, 0 ) 
			end
		else
			outputChatBox ( "Du bist in keiner Fraktion!", 255, 0, 0 )
		end
	else
		outputChatBox ( "Gebrauch: /fraktioncommands  [0-5]", 255, 0, 0 ) 
	end
end )


local allAdminCommands = {
	[0] = { "/a [Text] - Benutzt den VIP Chat (nur für VIP)",
			"/muted [Name] - (Ent-)Mutet einen Spieler (nur VIP)",
			"/premium - Öffnet das Premium-Panel",
			"/status [Status] - Ändert den Status" },
	-- [1] Supporter
	[1] = { "/report - Portet dich in die Report-Halle",
			"/leavereport - Verlässt die Report-Halle",
			"/getchangestate [Name] - Prüft letzten Invite/Uninvite des Spielers",
			"/o [Text] - Benutzt den öffentlichen Serverchat (Ochat)",
			"/akn - Beendet eine laufende Aktion",
			"/adchat - Aktiviert/Deaktiviert den Ad-Chat",
			"/a [Text] - Benutzt den internen Adminchat",
			"/move [Richtung] - Portet dich etwas in die Richtung",
			"/freezen [Name] - Freezt einen Spieler",
			"/flip - Dreht ein umgekipptes Fahrzeug um",
			"/payday coins - Startet/Beendet ein Payday-Coins-Event",
			"/mark [1-3] - Legt eine Markierung",
			"/gotomark [1-3] - Portet zu der Markierung",
			"/spec [Name] - Spectet jemanden",
			"/rkick [Name] [Grund] - Kickt jemanden",
			"/goto [Name] - Portet zu einem Spieler",
			"/gethere [Name] - Portet einen Spieler zu sich",
			"/rmute [Name] - Mutet einen Spieler",
			"/crespawn [Radius] - Respawnt Fahrzeuge im Radius",
			"/gotocar [Name] [Slot] - Portet zum Auto eines Spielers",
			"/getcar [Name] [Slot] - Portet ein Auto eines Spielers her",
			"/prison [Name] [Zeit] [Grund] - Steckt jemanden ins Prison",
			"/warn [Name] [Tage] [Grund] - Gibt einen Warn",
			"/smode - Geht Adminduty",
	        "/aduty - Geht Adminduty",
			"/amode - Geht Adminduty",
			"/supportmode - Geht Adminduty",
			"/ausknasten [Name] [Ziel] - Knastet jemanden aus",
			"/pm [Name] [Nachricht] - Schreibt jemandem eine private Nachricht",
			"/delallreporterblips - Löscht alle Reporter-Blips",
			"/acar [ID] - Gibt sich ein Admin-Fahrzeug",
			"/update [Ressource] - Startet ein manuelles Update",
			"/websync - Synchronisiert Spielerdaten mit dem Webpanel",
			"/desat [Grund] - Zerstört den laufenden Atomtransport" },
	-- [2] Moderator
	[2] = { "/respawn [Typ] - Respawnt Fahrzeuge",
			"/intdim [Name] [Interior] [Dimension] - Setzt jemanden in Interior & Dimension",
			"/cc - Säubert den Chat",
			"/setrank [Name] [Rang] - Setzt jemandem den Rang in seiner Fraktion",
			"/makeleader [Name] [FraktionsID] - Setzt jemanden als Leader ein",
			"/heal [Name] - Belebt einen Spieler wieder / heilt ihn",
			"/tban [Name] [Zeit] [Grund] - Bannt jemanden für eine Zeit",
			"/entban [Name] - Entbannt einen Spieler",
			"/newhouse [Preis] [Interior] - Erstellt einen Interior",
			"/iraum [Interior] - Portet in einen Interior",
			"/rnails - Löscht alle platzierten Nagelbänder",
			"/resetcarrob - Setzt den Carrob-Cooldown zurück" },
	-- [3] Administrator
	[3] = { "/setnailmax [Anzahl] - Ändert die max. Anzahl der Nagelbänder im Auto",
			"/rban [Name] [Grund] - Bannt jemanden permanent",
			"/aweather - Ändert das Wetter",
			"/deletewarn [Name] - Löscht alle Warns",
			"/nickchange [Name] [NeuerName] - Führt einen Nickchange aus",
			"/pwchange [Name] [PW] - Führt eine Passwort-Änderung aus",
			"/rcheck [Name] - Überprüft einen Spieler",
			"/tunecar [Part] - Tunet ein Fahrzeug",
			"/getip [Name] - Fragt IP vom Spieler ab",
			"/skydive [Name] - Skydivet einen Spieler",
			"/astart - Startet ein Auto",
			"/aenter - Betretet ein Auto",
			"/delhouse - Löscht den Haus-Marker",
			"/makefft - Lässt ein Auto FFT werden (ohne Motor)",
			"/getinfo [Name] - Zeigt spielerbezogene Informationen an",
			"/kickall [Grund] - Kickt alle Spieler",
			"/beta code [Anzahl] | grant [Name] | revoke [Name] | status - Beta-Zugangscode-System",
			"/map - Öffnet die Vollbild-Karte",
			"/resetbombe - Setzt eine feststeckende Terroristen-Bombe zurück" },
	-- [4] Stellv. Projektleiter
	[4] = { "/shut - Notabschaltung",
			"/give [Name] [coin/geld/bankgeld] [Anzahl] - Gibt einem Spieler Coins, Bargeld oder Bankgeld",
			"/changeprompt ... - Ändert einen Ankündigungstext (Prompt)" },
	-- [5] Projektleiter
	[5] = { "/gmx [Minuten] - Restartet den Server",
			"/adminlevel [Name] [Rang] - Gibt jemandem Adminrang",
			"/setPremium [Name] [Tage] [Paket] - Vergibt Premium an einen Spieler",
            "/savedata - Speichert alle Spielerdaten sofort",
			"/setlevel [Name] [Level] - Setzt das Level eines Spielers",
			"/delacc [Name] - Löscht den Account eines Spielers unwiderruflich",
			"/restartresource - Speichert alle Spieler und startet die Ressource neu",
			"/makeadmin [Name] [Rang] - Gibt jemandem Adminrang (Alias von /adminlevel)" },
	-- [6] Entwickler
	[6] = { "/pos - Zeigt die eigene Position (x/y/z/int/dim)",
			"/tpto [x] [y] [z] [int] [dim] - Teleportiert zu Koordinaten",
			"/addwhitelist [Name] [Serial] - Fügt einen Spieler zur Whitelist hinzu",
			"/wh - Aktiviert/Deaktiviert die Whitelist" }
}


addCommandHandler ( "admincommands", function ( cmd, rang )
	if rang then
		local rang = tonumber ( rang )
		if rang and rang >= 1 and rang <= 6 then
			outputChatBox ( "Befehle:", 200, 200, 200 )
			for i=1, #allAdminCommands[rang] do
				outputChatBox ( allAdminCommands[rang][i], 200, 200, 0 )
				wasthere = true
			end
		else
			outputChatBox ( "Gebrauch: /admincommands  [1-6]", 255, 0, 0 ) 
		end
	else
		outputChatBox ( "Gebrauch: /admincommands  [1-6]", 255, 0, 0 ) 
	end
end)
 
